# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7f1b1ea73535a541a88739d80125ef4b"
application_url = "https://welding-spain-dancing-affected.trycloudflare.com"
embedded = true
name = "client-creds-tophat"
handle = "client-creds-tophat"

[build]
include_config_on_deploy = true
dev_store_url = "development-store-1.shopify.fa-jan28.fwaad-ahmad.us.spin.dev"
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://welding-spain-dancing-affected.trycloudflare.com/auth/callback",
  "https://welding-spain-dancing-affected.trycloudflare.com/auth/shopify/callback",
  "https://welding-spain-dancing-affected.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
